import React from 'react';

export const CplusplusIntro = () => {
    return (
        <div className='text-start p-5'>
        <h1>C++ Introduction</h1><br /><br /><hr />
        <h6>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae quidem quisquam impedit dignissimos voluptatibus quaerat inventore optio soluta tenetur repellendus culpa possimus, rem perspiciatis a magnam, earum qui nisi odit! Ad, necessitatibus molestiae! Molestias ad optio ducimus tenetur sit numquam dolorum soluta est fuga aperiam. Quos culpa cum nobis quibusdam vero, nemo tempora odio natus rem totam enim nihil deleniti voluptatibus, a odit maiores aut sapiente accusamus sit tempore molestiae earum saepe. Fuga et assumenda ipsum voluptatem soluta eos dolorum nisi illum ratione, ad qui aperiam deserunt quidem accusantium delectus perferendis dolorem explicabo possimus quos unde ut necessitatibus corrupti a neque! Fugit obcaecati repellendus optio id sapiente voluptate sit, distinctio, aliquid ducimus aliquam maiores! Possimus aliquam accusantium minus voluptatibus nihil fuga odio consectetur provident unde rem, quam deleniti necessitatibus quo natus tenetur iste? Dolorem, animi? Omnis doloremque harum quibusdam eaque ratione at quis, molestias nobis porro incidunt assumenda doloribus laboriosam cumque quidem voluptas in asperiores deleniti illum sapiente minus quod provident? Possimus praesentium nam consequuntur necessitatibus modi animi ullam non voluptatem magni officiis dolor placeat suscipit repellat libero atque vitae, maiores recusandae aliquam officia, voluptate error. Libero quae sint accusantium, assumenda corporis provident ipsam iusto est molestias voluptatibus repellat minima iure debitis sequi laborum quis reiciendis dicta a natus? Voluptatibus voluptas sed ut deserunt minima consectetur nostrum nisi, facere hic repudiandae iusto sequi quia. Ea nemo adipisci, mollitia quibusdam, reprehenderit, itaque praesentium odio magnam eos ex tenetur dolore cumque aliquid. Tenetur necessitatibus fuga quam reiciendis dignissimos, provident harum exercitationem eius debitis, assumenda officiis. Ex adipisci qui ipsam fugiat nihil, ducimus nostrum maiores nulla expedita recusandae id! Enim rerum voluptatem ea nostrum consequuntur corrupti eaque, veniam, unde illum aperiam adipisci a provident, nihil ullam asperiores fugiat iste! Similique aliquid repellat sit quam cumque quidem voluptas exercitationem accusantium quasi, omnis aliquam sed.</h6>
    </div>);
};
